const mongoose = require('mongoose');
const config = require('../src/config/config');
const { Role } = require('../src/models');

const seedRoles = async () => {
    try {
        await mongoose.connect(config.mongoose.url, config.mongoose.options);
        console.log('Connected to MongoDB');

        const roles = [
            {
                roleName: 'Admin',
                isSystemRole: true,
                description: 'System Administrator with full access',
                permissions: {
                    canViewOrganizations: true,
                    canViewOwnOrganization: true,
                    canCreateOrganizations: true,
                    canUpdateOrganizations: true,
                    canDeleteOrganizations: true,
                    canViewRoles: true,
                    canManageRoles: true,
                    canViewUsers: true,
                    canViewManageOwnUser: true,
                    canUpdateUser: true,
                    canDeleteUser: true,
                    canCreateUser: true,
                    canViewLeads: true,
                    canManageLeads: true,
                    canViewTeams: true,
                    canManageTeams: true,
                    canViewDeals: true,
                    canManageDeals: true,
                    canViewStatus: true,
                    canManageStatus: true,
                    canViewSettings: true,
                    canManageSettings: true,
                    canViewGoals: true,
                    canManageGoals: true,
                    canViewCalls: true,
                    canManageCalls: true,
                    canViewMailBox: true,
                    canManageMailBox: true,
                    canViewTasks: true,
                    canManageTasks: true,
                    canViewNotes: true,
                    canManageNotes: true,
                    canViewArticles: true,
                    canManageArticles: true,
                    canViewWiki: true,
                    canManageWiki: true,
                    canViewEmailTemplates: true,
                    canManageEmailTemplates: true,
                    canViewEmailFolders: true,
                    canManageEmailFolders: true,
                    canViewEmailCampaigns: true,
                    canManageEmailCampaigns: true,
                    canViewScoreQuestions: true,
                    canManageScoreQuestions: true,
                    canViewFiles: true,
                    canManageFiles: true,
                    canViewKeyTokens: true,
                    canManageKeyTokens: true,
                    canViewPrompts: true,
                    canManagePrompts: true,
                    canViewOverviews: true,
                    canManageOverviews: true,
                    canViewPromptTemplates: true,
                    canManagePromptTemplates: true,
                    canViewForms: true,
                    canManageForms: true,
                    canViewActivities: true,
                    canManageActivities: true,
                    canViewMails: true,
                    canManageMails: true,
                    canViewTags: true,
                    canManageTags: true,
                    canViewLemCampaigns: true,
                    canManageLemCampaigns: true,
                    canViewPipelines: true,
                    canManagePipelines: true,
                    canViewPlans: true,
                    canManagePlans: true,
                    canViewSubscriptions: true,
                    canManageSubscriptions: true,
                    canManageInvoice: true,
                    canManageLinks: true,
                    canViewLinks: true,
                    canViewCompanies: true,
                    canManageCompanies: true,
                    canViewSnippets: true,
                    canManageSnippets: true,
                    canViewCampaigns: true,
                    canManageCampaigns: true,
                    canManageHelp: true,
                    canViewHelp: true,
                    canViewRecurringEmails: true,
                    canManageRecurringEmails: true,
                    canViewContacts: true,
                    canManageContacts: true,
                    canViewSegments: true,
                    canManageSegments: true,
                }
            },
            {
                roleName: 'User',
                isSystemRole: true,
                description: 'Standard User with restricted access',
                permissions: {
                    canViewOrganizations: false,
                    canViewOwnOrganization: true,
                    canCreateOrganizations: false,
                    canUpdateOrganizations: false,
                    canDeleteOrganizations: false,
                    canViewRoles: false,
                    canManageRoles: false,
                    canViewUsers: true,
                    canViewManageOwnUser: true,
                    canUpdateUser: false,
                    canDeleteUser: false,
                    canCreateUser: false,
                    canViewLeads: true,
                    canManageLeads: true,
                    canViewTeams: true,
                    canManageTeams: false,
                    canViewDeals: true,
                    canManageDeals: true,
                    canViewStatus: true,
                    canManageStatus: false,
                    canViewSettings: true,
                    canManageSettings: false,
                    canViewGoals: true,
                    canManageGoals: false,
                    canViewCalls: true,
                    canManageCalls: false,
                    canViewMailBox: true,
                    canManageMailBox: false,
                    canViewTasks: true,
                    canManageTasks: true,
                    canViewNotes: true,
                    canManageNotes: true,
                    canViewArticles: true,
                    canManageArticles: false,
                    canViewWiki: true,
                    canManageWiki: false,
                    canViewEmailTemplates: true,
                    canManageEmailTemplates: false,
                    canViewEmailFolders: true,
                    canManageEmailFolders: true,
                    canViewEmailCampaigns: false,
                    canManageEmailCampaigns: false,
                    canViewScoreQuestions: false,
                    canManageScoreQuestions: false,
                    canViewFiles: true,
                    canManageFiles: true,
                    canViewKeyTokens: true,
                    canManageKeyTokens: false,
                    canViewPrompts: true,
                    canManagePrompts: false,
                    canViewOverviews: true,
                    canManageOverviews: false,
                    canViewPromptTemplates: false,
                    canManagePromptTemplates: false,
                    canViewForms: true,
                    canManageForms: false,
                    canViewActivities: true,
                    canManageActivities: false,
                    canViewMails: true,
                    canManageMails: true,
                    canViewTags: true,
                    canManageTags: false,
                    canViewLemCampaigns: false,
                    canManageLemCampaigns: false,
                    canViewPipelines: true,
                    canManagePipelines: false,
                    canViewPlans: false,
                    canManagePlans: false,
                    canViewSubscriptions: false,
                    canManageSubscriptions: false,
                    canManageInvoice: false,
                    canManageLinks: true,
                    canViewLinks: true,
                    canViewCompanies: true,
                    canManageCompanies: false,
                    canViewSnippets: true,
                    canManageSnippets: false,
                    canViewCampaigns: false,
                    canManageCampaigns: false,
                    canManageHelp: true,
                    canViewHelp: true,
                    canViewRecurringEmails: false,
                    canManageRecurringEmails: false,
                    canViewContacts: true,
                    canManageContacts: true,
                    canViewSegments: false,
                    canManageSegments: false,
                }
            }
        ];

        for (const roleData of roles) {
            const existing = await Role.findOne({ roleName: roleData.roleName, isSystemRole: true });
            if (!existing) {
                await Role.create(roleData);
                console.log(`Created role: ${roleData.roleName}`);
            } else {
                console.log(`Role already exists: ${roleData.roleName}`);
            }
        }

        console.log('Roles seeding completed');
    } catch (error) {
        console.error('Error seeding roles:', error);
    } finally {
        await mongoose.disconnect();
    }
};

seedRoles();
